config/routes.rb
Rails.application.routes.draw do
  resources :diligences
  resources :correspondentes
  resources :clientes

  root 'diligences#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/correspondente.rb
class Correspondente < ActiveRecord::Base

	email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

	validates :email, :presence => true,
	          :format           => { :with => email_regex },
	          :uniqueness       => { :case_sensitive => false } 
end

app/models/diligence.rb
class Diligence < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nome, :oab, :cpf, :email, :telefone, :endereco, :cidade, :uf)
    end
end

app/controllers/correspondentes_controller.rb
class CorrespondentesController < ApplicationController
  before_action :set_correspondente, only: [:show, :edit, :update, :destroy]

  # GET /correspondentes
  # GET /correspondentes.json
  def index
    @correspondentes = Correspondente.all
  end

  # GET /correspondentes/1
  # GET /correspondentes/1.json
  def show
  end

  # GET /correspondentes/new
  def new
    @correspondente = Correspondente.new
  end

  # GET /correspondentes/1/edit
  def edit
  end

  # POST /correspondentes
  # POST /correspondentes.json
  def create
    @correspondente = Correspondente.new(correspondente_params)

    respond_to do |format|
      if @correspondente.save
        format.html { redirect_to @correspondente, notice: 'Correspondente was successfully created.' }
        format.json { render :show, status: :created, location: @correspondente }
      else
        format.html { render :new }
        format.json { render json: @correspondente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /correspondentes/1
  # PATCH/PUT /correspondentes/1.json
  def update
    respond_to do |format|
      if @correspondente.update(correspondente_params)
        format.html { redirect_to @correspondente, notice: 'Correspondente was successfully updated.' }
        format.json { render :show, status: :ok, location: @correspondente }
      else
        format.html { render :edit }
        format.json { render json: @correspondente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correspondentes/1
  # DELETE /correspondentes/1.json
  def destroy
    @correspondente.destroy
    respond_to do |format|
      format.html { redirect_to correspondentes_url, notice: 'Correspondente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correspondente
      @correspondente = Correspondente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correspondente_params
      params.require(:correspondente).permit(:nome, :cpf, :telefone, :email, :cidade, :uf, :observacao)
    end
end

app/controllers/diligences_controller.rb
class DiligencesController < ApplicationController
  before_action :set_diligence, only: [:show, :edit, :update, :destroy]

  # GET /diligences
  # GET /diligences.json
  def index
    @diligences = Diligence.all
  end

  # GET /diligences/1
  # GET /diligences/1.json
  def show
  end

  # GET /diligences/new
  def new
    @diligence = Diligence.new
  end

  # GET /diligences/1/edit
  def edit
  end

  # POST /diligences
  # POST /diligences.json
  def create
    @diligence = Diligence.new(diligence_params)

    respond_to do |format|
      if @diligence.save
        format.html { redirect_to @diligence, notice: 'Diligence was successfully created.' }
        format.json { render :show, status: :created, location: @diligence }
      else
        format.html { render :new }
        format.json { render json: @diligence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diligences/1
  # PATCH/PUT /diligences/1.json
  def update
    respond_to do |format|
      if @diligence.update(diligence_params)
        format.html { redirect_to @diligence, notice: 'Diligence was successfully updated.' }
        format.json { render :show, status: :ok, location: @diligence }
      else
        format.html { render :edit }
        format.json { render json: @diligence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diligences/1
  # DELETE /diligences/1.json
  def destroy
    @diligence.destroy
    respond_to do |format|
      format.html { redirect_to diligences_url, notice: 'Diligence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diligence
      @diligence = Diligence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diligence_params
      params.require(:diligence).permit(:titulo, :corpo, :status, :data_inicio, :data_fim)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/correspondentes_helper.rb
module CorrespondentesHelper
end

app/helpers/diligences_helper.rb
module DiligencesHelper
end

app/views/clientes/_form.html.erb
<%= form_for @cliente, :html => { :class => "form-horizontal cliente" } do |f| %>

  <% if @cliente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @cliente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :oab, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :oab, :class => 'form-control' %>
    </div>
    <%=f.error_span(:oab) %>
  </div>
  <div class="form-group">
    <%= f.label :cpf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cpf) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>
  <div class="form-group">
    <%= f.label :endereco, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :endereco, :class => 'form-control' %>
    </div>
    <%=f.error_span(:endereco) %>
  </div>
  <div class="form-group">
    <%= f.label :cidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cidade) %>
  </div>
  <div class="form-group">
    <%= f.label :uf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :uf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:uf) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                clientes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clientes/edit.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/index.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:oab) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:endereco) %></th>
      <th><%= model_class.human_attribute_name(:cidade) %></th>
      <th><%= model_class.human_attribute_name(:uf) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= link_to cliente.id, cliente_path(cliente) %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.oab %></td>
        <td><%= cliente.cpf %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.endereco %></td>
        <td><%= cliente.cidade %></td>
        <td><%= cliente.uf %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_cliente_path(cliente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      cliente_path(cliente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_cliente_path,
            :class => 'btn btn-primary' %>

app/views/clientes/new.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/clientes/show.html.erb
<%- model_class = Cliente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @cliente.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:oab) %>:</strong></dt>
  <dd><%= @cliente.oab %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @cliente.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @cliente.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @cliente.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @cliente.endereco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cidade) %>:</strong></dt>
  <dd><%= @cliente.cidade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uf) %>:</strong></dt>
  <dd><%= @cliente.uf %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              clientes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_cliente_path(@cliente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              cliente_path(@cliente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/correspondentes/_form.html.erb
<%= form_for @correspondente, :html => { :class => "form-horizontal correspondente" } do |f| %>

  <% if @correspondente.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@correspondente.errors.count, "error") %> prohibited this correspondente from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @correspondente.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :cpf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cpf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cpf) %>
  </div>
  <div class="form-group">
    <%= f.label :telefone, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :telefone, :class => 'form-control' %>
    </div>
    <%=f.error_span(:telefone) %>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :cidade, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cidade, :class => 'form-control' %>
    </div>
    <%=f.error_span(:cidade) %>
  </div>
  <div class="form-group">
    <%= f.label :uf, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :uf, :class => 'form-control' %>
    </div>
    <%=f.error_span(:uf) %>
  </div>
  <div class="form-group">
    <%= f.label :observacao, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :observacao, :class => 'form-control' %>
    </div>
    <%=f.error_span(:observacao) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                correspondentes_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/correspondentes/edit.html.erb
<%- model_class = Correspondente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/correspondentes/index.html.erb
<%- model_class = Correspondente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:cpf) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:cidade) %></th>
      <th><%= model_class.human_attribute_name(:uf) %></th>
      <th><%= model_class.human_attribute_name(:observacao) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @correspondentes.each do |correspondente| %>
      <tr>
        <td><%= link_to correspondente.id, correspondente_path(correspondente) %></td>
        <td><%= correspondente.nome %></td>
        <td><%= correspondente.cpf %></td>
        <td><%= correspondente.telefone %></td>
        <td><%= correspondente.email %></td>
        <td><%= correspondente.cidade %></td>
        <td><%= correspondente.uf %></td>
        <td><%= correspondente.observacao %></td>
        <td><%=l correspondente.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_correspondente_path(correspondente), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      correspondente_path(correspondente),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_correspondente_path,
            :class => 'btn btn-primary' %>

app/views/correspondentes/new.html.erb
<%- model_class = Correspondente -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/correspondentes/show.html.erb
<%- model_class = Correspondente -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @correspondente.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cpf) %>:</strong></dt>
  <dd><%= @correspondente.cpf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @correspondente.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @correspondente.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cidade) %>:</strong></dt>
  <dd><%= @correspondente.cidade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:uf) %>:</strong></dt>
  <dd><%= @correspondente.uf %></dd>
  <dt><strong><%= model_class.human_attribute_name(:observacao) %>:</strong></dt>
  <dd><%= @correspondente.observacao %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              correspondentes_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_correspondente_path(@correspondente), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              correspondente_path(@correspondente),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/diligences/edit.html.erb
<%- model_class = Diligence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/diligences/index.html.erb
<%- model_class = Diligence -%>
<div class="page-header">
  <h1> Diligencias </h1>
</div>
<table class="table table-striped">
  <thead>
  <div class="row">
    <tr>
      <!--<th><#%= model_class.human_attribute_name(:id) %></th>-->
      <th class="col-md-2"><%= model_class.human_attribute_name(:titulo) %></th>
      <th class="col-md-3"><%= model_class.human_attribute_name(:corpo) %></th>
      <th class="col-md-1"><%= model_class.human_attribute_name(:status) %></th>
      <th class="col-md-2"><%= model_class.human_attribute_name(:data_inicio) %></th>
      <th class="col-md-2"><%= model_class.human_attribute_name(:data_fim) %></th> 
      <th class="col-md-4">Opções</th>
    </tr>
  </thead>
  <tbody>
    <% @diligences.each do |diligence| %>
      <tr>
        <!--<td><#%= link_to diligence.id, diligence_path(diligence) %></td>-->''
        <td class="col-md-0"><%= diligence.titulo %></td>
        <td class="col-md-3"><%= diligence.corpo %></td>
        <td class="col-md-1"><%= diligence.status %></td>
        <td class="col-md-2"><%= diligence.data_inicio %></td>
        <td class="col-md-2"><%= diligence.data_fim %></td>
        <td>
 
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      diligence_path(diligence), :class => 'btn btn-default btn-xs', :class => 'btn btn-xs btn-success' %>

          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_diligence_path(diligence), :class => 'btn btn-default btn-xs' %>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      diligence_path(diligence),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      </div>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diligence_path,
            :class => 'btn btn-primary' %>

app/views/diligences/new.html.erb
<%- model_class = Diligence -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ProjectDiligence" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Rtina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Sistema de Diligence</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <!--<li><#%= link_to "Inicio", ""  %></li>-->
            <li><%= link_to "Diligencias", diligences_path  %></li>
            <li><%= link_to "Clientes", clientes_path  %></li>
            <li><%= link_to "Correspondentes", correspondentes_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
    </div> <!-- /container -->

  </body>
</html>